name: wild_trace
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  country_picker: ^2.0.27
  intl: ^0.20.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  flutter_stripe: ^10.1.1
  flutter_dotenv: ^6.0.0
  quickalert: ^1.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  battery_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/heroimageh1.jpg
    - assets/images/heroimageaboutus.jpg
    - assets/images/heroimagegallery.jpg
    - assets/images/communitywork2.jpg
    - assets/images/natgeo.png
    - assets/images/bbcearth.jpg
    - assets/images/nhmwpy.jpg
    - assets/images/team.jpg
    - .env
